# These substitutions allow the end user to override certain values
substitutions:
  name: boot-30a-2x-01
  uppername: Boot 30A 2x 01
  lowername: boot_30a_2x_01
  version: '1.0'

packages:
  device_base: !include common/device_base.yaml
  wifi: !include common/wifi.yaml

esp8266:
  board: esp01_1m
  restore_from_flash: true

ota:
  password: "d03d1ffd17e573ad6f6d88881b463486"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "${uppername} Onboard Button"
  - platform: gpio
    pin:
      number: GPIO4
      mode:
        input: true
        pullup: true
      inverted: true
    name: "${uppername} Button 04"
  - platform: gpio
    pin:
      number: GPIO15
      mode:
        input: true
        pullup: true
      inverted: false
    name: "${uppername} Button 15"
  - platform: gpio
    pin:
      number: GPIO13
      mode:
        input: true
        pullup: true
      inverted: true
    name: "${uppername} Button 13"
    on_press:
      then:
        - switch.toggle: relay_1
  - platform: gpio
    pin:
      number: GPIO16
      mode:
        input: true
    name: "${uppername} Button 16"
  - platform: gpio
    pin:
      number: GPIO01
      mode:
        input: true
    name: "${uppername} Button 01"
  - platform: gpio
    pin:
      number: GPIO03
      mode:
        input: true
      inverted: true
    name: "${uppername} Button 03"
    
switch:
  - platform: gpio
    name: "${uppername} Relay 1"
    pin: GPIO14
    id: relay_1
    on_turn_on:
    - light.turn_on: blue_led
    on_turn_off:
    - light.turn_off: blue_led
  - platform: gpio
    name: "${uppername} Relay 2"
    pin: GPIO12
    id: relay_2

output:
  # onboard led
  - platform: gpio
    id: onboard_led_pin
    pin: GPIO02
    inverted: true
  # blue led
  - platform: gpio
    id: blue_led_pin
    pin: GPIO05
    inverted: true

light:
  - platform: binary
    name: "${uppername} Onboard LED"
    output: onboard_led_pin
    id: onboard_led
  - platform: binary
    name: "${uppername} Blue LED"
    output: blue_led_pin
    id: blue_led