# These substitutions allow the end user to override certain values
substitutions:
  name: boot-30a-2x-01
  device_description: "Boot 2x 30A Relay board"
  uppername: Boot 30A 2x 01
  lowername: boot_30a_2x_01
  version: '1.1'

packages:
  device_base: !include common/device_base.yaml
  wifi: !include common/wifi.yaml

esp8266:
  board: esp01_1m
  restore_from_flash: true

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "${uppername} IO 00 (B1 + Onboard Button)"
    on_press:
      then:
        - switch.toggle: ${lowername}_ry_1
  - platform: gpio
    pin:
      number: GPIO4
      mode:
        input: true
        pullup: true
      inverted: true
    name: "${uppername} IO 04 (B2)"
    on_press:
      then:
        - switch.toggle: ${lowername}_ry_2

# # GPIO pins 1, 3 and 15 are still available, as are 2 and 5 but linked to leds
# # (https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/)
#
#   - platform: gpio
#     name: "${uppername} IO 01"
#     pin:
#       number: GPIO01
#       mode:
#         input: true
#   - platform: gpio
#     name: "${uppername} IO 03"
#     pin:
#       number: GPIO03
#       mode:
#         input: true
#       inverted: true
#   - platform: gpio
#     name: "${uppername} IO 15"
#     pin:
#       number: GPIO15
#       mode:
#         input: true
#         pullup: true
#       inverted: false

# linking relay switch state with it's led output
switch:
  - platform: gpio
    name: "${uppername} Relay 1"
    pin: GPIO14
    id: ${lowername}_ry_1
    on_turn_on:
    - output.turn_on: "${lowername}_L1_pin"
    on_turn_off:
    - output.turn_off: "${lowername}_L1_pin"
  - platform: gpio
    name: "${uppername} Relay 2"
    pin: GPIO12
    id: ${lowername}_ry_2
    on_turn_on:
    - output.turn_on: "${lowername}_L2_pin"
    on_turn_off:
    - output.turn_off: "${lowername}_L2_pin"

output:
  # onboard led
  - platform: gpio
    id: ${lowername}_onboard_led_pin
    pin: GPIO02
    inverted: true
  # external blue led
  - platform: gpio
    id: ${lowername}_blue_led_pin
    pin: GPIO05
    inverted: true
  # Button 02 LED pin
  - platform: gpio
    id: "${lowername}_L2_pin"
    pin: GPIO13
    inverted: true
  # Button 01 LED pin
  - platform: gpio
    id: "${lowername}_L1_pin"
    pin: GPIO16
    inverted: true

light:
  - platform: binary
    name: "${uppername} Onboard LED"
    output: ${lowername}_onboard_led_pin
    id: ${lowername}_onboard_led
  - platform: binary
    name: "${uppername} Blue LED"
    output: ${lowername}_blue_led_pin
    id: ${lowername}_blue_led
