  - platform: wifi_info
    ip_address:
      name: "${uppername} IP"
      entity_category: diagnostic
    ssid:
      name: "${uppername} SSID"
      entity_category: diagnostic
    bssid:
      name: "${uppername} BSSID"
      entity_category: diagnostic
    mac_address:
      name: "${uppername} MAC"
      entity_category: diagnostic