  - platform: wifi_info
    ip_address:
      name: "IP"
      entity_category: diagnostic
    ssid:
      name: "SSID"
      entity_category: diagnostic
    bssid:
      name: "BSSID"
      entity_category: diagnostic
    mac_address:
      name: "MAC"
      entity_category: diagnostic