
  - platform: uptime
    id: uptime_s
    update_interval: 120s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: ${lowername}_uptime
            state: !lambda |-
              int seconds = round(id(${lowername}_uptime_s).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? String(days) + "d " : "") +
                (hours ? String(hours) + "h " : "") +
                (minutes ? String(minutes) + "m " : "") +
                (String(seconds) + "s")
              ).c_str();